"""Constants for the AVE dominaplus integration."""

DOMAIN = "ave_dominaplus"
BRAND_PREFIX = "AVE dominaplus"

AVE_FAMILY_SWITCH = 1
AVE_FAMILY_DIMMER = 2
AVE_FAMILY_THERMOSTAT = 4
AVE_FAMILY_SCENARIO = 6
AVE_FAMILY_ANTITHEFT = 7
AVE_FAMILY_CAMERA = 8
AVE_FAMILY_KEYPAD = 11
AVE_FAMILY_ANTITHEFT_AREA = 12
AVE_FAMILY_MOTION_SENSOR = 1007
